@startuml
!theme toy
scale 1.5

actor "Пользователь" as user
participant "Frontend" as f
participant "Backend" as b
participant "Server" as s

title Просмотр пользователем истории заказов в рамках компании
group  Проверка истории
                user -> f: Авторизация и переход на страницу "Мои заказы"
                f -> b: Запрос данных о пользователе
                b -> s: Запрос данных о пользователе 
                s -> b: Передача данных о пользователе
                b -> f: 
        else иногда происходит ручное обновление
                admin -> hr: Обновить контракт сотрудника
              hr -> kafka: Отправить сообщение о изменении статуса сотрудника
end


@enduml
